name: Build CMD Start Page

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - name: Checkout source
      uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Run Yarn Install
      uses: borales/actions-yarn@v2.0.0
      with:
        cmd: install # will run `yarn install` command
    - name: Run Yarn Build
      uses: borales/actions-yarn@v2.0.0
      with:
        cmd: build # will run `yarn build` command


